spring:
  application:
    name: history-excerptor
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT:5432}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

schema:
  name: ${DB_SCHEMA:registry}
  historyTableSuffix: _hst

signature:
  enabled: true

thirdPartySystems:
  accessToken: ${ACCESS_TOKEN}

excerpt:
  url: ${EXCERPT_URL}
  statusCheck:
    maxAttempts: 10

dso:
  url: ${DSO_URL}

storage:
  request-signature-form-data-storage:
    type: redis
    backend:
      redis:
        password: ${REDIS_PASSWORD}
        sentinel:
          master: ${REDIS_MASTER}
          nodes: ${REDIS_ENDPOINT}
      ceph:
        http-endpoint: ${REQUEST_SIGNATURE_CEPH_HTTP_ENDPOINT}
        access-key: ${REQUEST_SIGNATURE_CEPH_ACCESS_KEY}
        secret-key: ${REQUEST_SIGNATURE_CEPH_SECRET_KEY}
        bucket: ${REQUEST_SIGNATURE_CEPH_BUCKET_NAME}
  historic-signature-form-data-storage:
    type: ceph
    backend:
      ceph:
        http-endpoint: ${HISTORIC_SIGNATURES_CEPH_HTTP_ENDPOINT}
        access-key: ${HISTORIC_SIGNATURES_CEPH_ACCESS_KEY}
        secret-key: ${HISTORIC_SIGNATURES_CEPH_SECRET_KEY}
        bucket: ${HISTORIC_SIGNATURES_CEPH_BUCKET_NAME}

s3:
  config:
    client:
      protocol: http
    options:
      pathStyleAccess: true

openshift:
  enabled: true
  namespace: ${OPENSHIFT_NAMESPACE}
  parentJob:
    name: ${OPENSHIFT_JOB}
    resultField: ${OPENSHIFT_RESULT_FIELD}