spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registry
    username: postgres
    password: qwerty
    
schema:
  name: public

signature:
  enabled: false

thirdPartySystems:
  accessToken: token

excerpt:
  url: localhost:7001

dso:
  url: https://dig-sign-ops-data-paradise-dev.apps.cicd2.mdtu-ddm.projects.epam.com

storage:
  request-signature-form-data-storage:
    type: redis
    backend:
      redis:
        password:
        sentinel:
          master: mymaster
          nodes: 127.0.0.1:26379
      ceph:
        http-endpoint: https://s3-openshift-storage.apps.cicd2.mdtu-ddm.projects.epam.com
        access-key: access-key
        secret-key: secret-key
        bucket: bucket
  historic-signature-form-data-storage:
    type: ceph
    backend:
      ceph:
        http-endpoint: https://s3-openshift-storage.apps.cicd2.mdtu-ddm.projects.epam.com
        access-key: access-key
        secret-key: secret-key
        bucket: bucket

openshift:
  enabled: false
  namespace: namespace
  parentJob:
    name: job
    resultField: result